services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: travel-app:latest
    container_name: travel_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - mysql
    networks:
      - travel-network

  nginx:
    image: nginx:alpine
    container_name: travel_nginx
    ports:
      - "8090:80"
    volumes:
      - .:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - travel-network

  mysql:
    image: mysql:8
    container_name: travel_mysql
    restart: unless-stopped
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: travel_db
      MYSQL_USER: travel
      MYSQL_PASSWORD: travel123
    volumes:
      - travel_mysql_data:/var/lib/mysql
    networks:
      - travel-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: travel_phpmyadmin
    restart: unless-stopped
    ports:
      - "8091:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql
    networks:
      - travel-network

volumes:
  travel_mysql_data:

networks:
  travel-network:
    driver: bridge
